name:                lambda
version:             0.2.0.0
github:              "githubuser/lambda"
license:             Apache2
author:              "Christoph stahl"
maintainer:          "christoph.stahl@tu-dortmund.de"
copyright:           "2019 Christoph Stahl"

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/lambda#readme>

dependencies:
- base >= 4.7 && < 5
- containers
- directory
- filepath
- mtl
- haskeline

library:
  source-dirs: src

executables:
  lambda:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - lambda
